### ISSUE TITLE
Get pantry doesn't return list of baskets

### ISSUE THREAD

**Issue by richcorbs** [imRohan/Pantry#19]
Hey, this looks neat so far.

When I GET my pantry there is a JSON key for `baskets: []` but it is an empty array.

I have a basket and can GET the basket using the API.

Should the basket names be displayed in the pantry's list of baskets?

**Comment by richcorbs** [comment]
Oh interesting, when the basket is named the same as the pantry it is not included in the list of baskets.

**Comment by richcorbs** [comment]
Or when the basket name matches the pantry name at all it doesn't show up in the list of baskets.

My pantry is named "richcorbs". Baskets "richcorbs" and "richcorbs2" do not show up in the GET pantry baskets list.

**Comment by richcorbs** [comment]
Maybe a GET for a record that doesn't exist could get a 404 instead of a 400? The request was fine but there wasn't a record.

**Comment by imRohan** [comment]
Ahh, thanks for the heads up! I believe you may be right, there may also be something wonky going on with how I'm retrieving the baskets.

**Comment by imRohan** [comment]
@richcorbs A fix for this issue was deployed early today. Closing the issue for now, but if the issue persists, ill reopen.
