### ISSUE TITLE
Post basket

### ISSUE THREAD

**Issue by tudorels** [imRohan/Pantry#28]
Hello,

I tried to create a basket, but I only get error:
Could not create basket: Validation failed: An instance of Block has failed the validation:
 - property payload has failed the following constraints: isNotEmptyObject 

Thanks

**Comment by imRohan** [comment]
Hey @tudorels, it seems like you're trying to create a basket without supplying any object as the payload. Can you please post the request payload of the `POST` request?

**Comment by tudorels** [comment]
https://getpantry.cloud/apiv1/pantry/myPantryID/basket/testbasket

like I saw in docs to create a basket

**Comment by tudorels** [comment]
Is mandatory to insert some data in basket. I can not create an emty basket? Why?

**Comment by imRohan** [comment]
Unfortunately yes, a basket cannot be empty. For now, would you be able to work around this limitation? In the meantime, I'll figure out a way to allow users to create empty baskets in their pantry.

**Comment by tudorels** [comment]
It's ok for now. I'm also interested in adding new data in basket along with other data already existing in basket, like adding new record in other database system. It is posible? I've seen the other issue and you said it will be posible with put method. It will be very usefull to add new record in basket. Thanks!

**Comment by imRohan** [comment]
Ok sounds good! I agree that adding new data to existing baskets is definitely useful, and ill probably go the `PUT` route. Going to close this issue for now and continue discussions on [this issue](https://github.com/imRohan/Pantry/issues/21 ) regarding the new update basket feature.

**Comment by imRohan** [comment]
@tudorels Just an update, I've added a `put` route to the API to allow users to add new data to an existing basket, you can check it out it [here](https://documenter.getpostman.com/view/3281832/SzmZeMLC?version=latest#f1c2c2b2-63d3-42f6-b30d-94b08ed68ca9)! Please let me know if this works better for you.

**Comment by tudorels** [comment]
Maybe, I don't understand how is working ... I've made a basket "users" and I tried to add some records like this:
{ "username":"tudor", "password":"test1234$"} - this is first user
{"username":"tedi", "password":"test1234$"} -second user added with put
when I query the basket I get only second user. Maybe the basket is not like a collection. You must clarify this, how can we use this in real world. If you want to introduce a new concept nosql database, you must explain the concept and it must be made to easy understand and use. Till now I don't understand how it must work ...and how I can use this service ...
Thank you!

**Comment by imRohan** [comment]
@tudorels The`put` route allows you to perform a deep merge of objects. It merges the new data you provide with the existing contents of the basket.

 For your use-case, perhaps look into structuring your basket with an array of users like so: 
`{
	"users": [ 
           { "username": "user1", "password": "pass123"}, 
           {"username": "user2", "password": "pass234"}
        ]
}`

That way you can add new users to your array by sending a `put` request with the body
`{
	"users": [ {"username": "user3", "password": "pass345"} ]
}`

The response of this `put` call will be an array of 3 users.
