### ISSUE TITLE
Question: How long do baskets last until they are deleted for inactivity?

### ISSUE THREAD

**Issue by lcrespom** [imRohan/Pantry#76]
Your home page says "Data is securely stored for as long as you and your users need it and is deleted after a period of inactivity".

How long is this period of inactivity? I am planning to develop a small web app that will be used by a single person, and would like to use the pantry JSON store initially, but still don't want the data to disappear after the weekend or, say, after 2 weeks of vacation.

Also, do you send warning e-mails before deleting the data?

Thank you,
Luis.

**Comment by imRohan** [comment]
Hi Luis,

Good question! Currently, Pantry will store data indefinitely if the data is being accessed regularly.

After **30** days of inactivity, baskets that have not been accessed will be removed. In addition, after **50** days of account-wide inactivity, the Pantry (and its baskets) will be deleted.

I currently do not send warning e-mails prior to deletion but can add this to the roadmap if needed.
