### ISSUE TITLE
Curl post request command not working in powershell

### ISSUE THREAD

**Issue by kaffarell** [imRohan/Pantry#78]
The curl request does exist in powershell (altough it is only a redirect to Invoke-WebRequest) but the provided arguments do not exist in windows.
An alternative would be to use this command:
```
Invoke-WebRequest -Uri 'https://....' -Method POST -ContentType 'application/json' -Body '{ "key": "value" }'
```
It would also be useful to display it on the page (on the landingRight.html). I would make a pull request, but sadly I have issues running the project locally...

**Comment by kaffarell** [comment]
Hey @imRohan if you have the time it would be really cool to have a short CONTRIBUTING.md file which explains the process of setting up a dev environment.

**Comment by imRohan** [comment]
@kaffarell Yup, that sounds good. I'll add one in the next few days once im back home.

**Comment by kaffarell** [comment]
Thanks a lot!

**Comment by imRohan** [comment]
@kaffarell Just an FYI but I added the steps for getting a local development environment setup in the README [Link to PR](https://github.com/imRohan/Pantry/pull/87/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
