### ISSUE TITLE
Order baskets by "creation date"

### ISSUE THREAD

**Issue by damien5215** [imRohan/Pantry#80]
The order of the "array basket" is not ordered according to the "creation date" of the basket. It would be better if the newest basket was added to the bottom of the array.

**Comment by imRohan** [comment]
I like this, seems pretty useful for most users. 👍

**Comment by damien5215** [comment]
I was loading the data to an array (JavaScript) and I realised this behaviour. I solved my problem by sorting the array before using it. Thanks for replying!
