### ISSUE TITLE
GitHub Actions?

### ISSUE THREAD

**Issue by AnnikaCodes** [imRohan/Pantry#83]
```ts
#!/usr/bin/env node

// TODO
// - Setup Travis or something to run pipelines and run tests

// Get External Deps
```

It looks like you already run unit tests through GitHub Actions. Is this comment obsolete, or something I could help with?
(I'm interested in contributing to your project, and this was the first thing I noticed while reading the source code.)

**Comment by imRohan** [comment]
@AnnikaCodes Yup, these comments were mostly for my own sanity and are now obsolete / can be removed!
