### ISSUE TITLE
Switch from tslint to typescript-eslint

### ISSUE THREAD

**Issue by imRohan** [imRohan/Pantry#88]
There's still one linter failure locally, but it's because `tslint` crashes. This bug was reported (https://github.com/palantir/tslint/issues/4949), but hasn't been fixed because `tslint` is deprecated. You might want to switch to `typescript-eslint` or another linting tool.

_Originally posted by @AnnikaCodes in https://github.com/imRohan/Pantry/issues/84#issuecomment-913977709_

**Comment by imRohan** [comment]
@kaffarell I'll assign this one to you if thats ok? 😄

**Comment by kaffarell** [comment]
@imRohan ok
