### ISSUE TITLE
Allow Pantry to Run in Development Mode

### ISSUE THREAD

**Issue by kaffarell** [imRohan/Pantry#90]
We have to somehow create a "development mode" for the app. The problem I am currently facing is that I have to remove code lines to bypass the recaptcha because I do not have a valid secret key, the next problem is that I don't have a sendgrid api key, so I cannot bypass the welcome email and don't get the PantryID. It would be useful if we somehow (I really don't have any idea how) 
 add a development mode to bypass the recaptcha easily (without modifying code) and printing the PantryID to the console without using sendgrid.

**Comment by kaffarell** [comment]
That would be a good idea! We could use the Define Plugin in webpack:
```js
module.exports = (env, argv) => {
    return {
        ....
        plugins: [
            new webpack.DefinePlugin({
                '__ENVIRONMENT__': JSON.stringify(argv.mode)
            }),
        ],
      ...
    }
};
```

and then call it like this:
```js
webpack --mode=development
```
and the in the code:
```js
console.log('Mode: ' + __ENVIRONMENT__);
```

**Comment by imRohan** [comment]
For Pantry, webpack is only used to build front-end assets so I'm not sure if using the `DefinePlugin` could help us to bypass the ReCaptcha, Slack, SendGrid logic.

**Comment by imRohan** [comment]
@kaffarell I've opened up a PR to address this issue, check it out [here](https://github.com/imRohan/Pantry/pull/96). This PR will stop Pantry from attempting to post to any 3rd party services (Slack/CRM) and disables the ReCaptcha. 

Just an FYI but when you create an account Pantry currently [log's the Pantry ID to your console](https://github.com/imRohan/Pantry/blob/d9d7d5e9ad3ec35f12b2ac9a2fd81f08a7c70bca/src/controllers/account.ts#L34)
